name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7.9'
    - run: python compile_cs.py
    - run: tree . /a /f
    - uses: actions/upload-artifact@v2
      with:
        name: csharp_ts
        path: ts.exe
