name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: where csc
    - run: csc /optimize /target:winexe /platform:x64 /out:ts.exe Program.cs
    - run: tree . /a /f
    - uses: actions/upload-artifact@v2
      with:
        path: ts.exe
